ProjectIgnis/CardScripts

official/c95515058.lua, unofficial/c511009652.lua, unofficial/c511600106.lua
Monster having the effect "gain x ATK for each Monster it points to" would have gained x ATK from Link Spell like Judgment Arrow
=> Fix Link Monster ATK boost from Link Spell

official/c39910367.lua
now the effect properly places appropriate counters on itself when a card with a spell counter is destroyed
=> Small fix "Magical Citadel of Endymion"

official/c16638212.lua
D.D. Sprite lists "Special Summon" as an option when you don't have a monster.
[https://cdn.discordapp.com/attachments/184324960842416129/697627557985517588/Screen_Shot_2020-04-08_at_10.01.52_PM.png](url)
=> Fix Bug for D.D. Sprite

official/c60461077.lua
It was not checking for linked zones on its special normal summon condition
=> Fix Gouki Rising Scorpio

official/c91842653.lua
tp parameter does not exist on funciton spcon, returning nil. This meant the condition check was only checking Toon World on the first player's field instead of their controller's
=> Fix Toon Summoned Skull

official/c14553285.lua, official/c1764972.lua, official/c37169670.lua, official/c38898779.lua, official/c61257789.lua, unofficial/c511002518.lua
The following are now considered to be listing "Assault Mode Activate" in their text:
- Hyper Psychic Blaster/Assault Mode
- Colossal Fighter/Assault Mode
- Arcanite Magician/Assault Mode
- Doomkaiser Dragon/Assault Mode
- Red Dragon Archfiend/Assault Mode (Anime)
"Stardust Dragon/Assault Mode" was already doing that, but it was updated to use the appropriate constant for it.
=> "/Assault Mode" monster updates

unofficial/c511005713.lua
It was able to tribute Link monsters although they are considered to not have any DEF at all.
=> Small fix for "Current Corruption Virus"

official/c13032689.lua, official/c55067058.lua, official/c83880087.lua, official/c94807487.lua, official/c98918572.lua
Concerned Cards:
- Xyz Unit
- Number 19: Freezadon
- Light Wing Shield
- Rising Sun Slash
- Zoodiac Gathering
Issue: Previously, the number of material used instead was hardcoded to 1, now it take the return value of the operation function
=> Fix cards with EFFECT_OVERLAY_REMOVE_REPLACE

unofficial/c511000673.lua
Fixed a typo in line 58.
SetReset should apply to e3 not e1.
I don't know why github wants to delete the whole file again.
I didn't change anything with respect to the indentation.
=> Small fix for "Gagaga Mirror Slash"

official/c14550855.lua
Discarding 2 cards should force you into sending 2 cards from Deck to the GY.
=> Small Fix for "Infernity Inferno"

skill/c300201009.lua
The opponent's hand will shuffle automatically if the player said no to shuffle the opponent's hand into his deck.
It's because opponent's original hand is still visible after the turn which the skill card was activate as long as the opponent doesn't shuffle his hand manually.
=> small fix millennium eye

official/c56256517.lua
Use the TurnCount as Turn Counter as activating the same card copy recovered from the GY would mess with the Card's Turn Counter
=> Fix "Ledger of Legerdemain"

pre-release/c100200183.lua
Shouldn't special summon same name card
Shouldn't be disabled if it leave the field when activated the 2nd effect
=> Fix "Eda the Sun Magician"

unofficial/c511009403.lua
The card should also be activatable if you and not the opponent activates the destroying effect.
=> Small Fix for "Performapal Sky Ring"

unofficial/c511002075.lua
Incorrectly allows Summons of non-Xyz monsters.
=> Small fix for "Bahamut Shark (manga)"

unofficial/c511001973.lua
(Talked to Larry126 about this before posting)
https://yugipedia.com/wiki/T.G._Recipro_Dragonfly_(anime)
There are two main issues with the current version of the script:
1: The effect states that after returning to deck/sending to graveyard a synchro monster, it will special summon the "SYNCHRO MONSTERS" used for its synchro summon, instead it currently summons EVERY monster that was used for its synchro summon, even non-synchro monsters. This version of the script fixes that, and the only materials that will get special summoned (if any) are going to be synchro monsters.
2: The game is supposed to ask you if you want to Special Summon the materials, due to an issue in the script it doesn't, that has been fixed.
=> Fix "T.G. Recipro Dragonfly (Anime)"

unofficial/c511000359.lua
Didn't activate due to previous use of 'IsExistingTarget' for monster in Deck.
=> Small fix for "Shadow's Light"

unofficial/c511004407.lua
Reset not tagged to correct effect. Allowed multiple attacks even after being removed from field
=> Fix "Destiny HERO - Dreamer (Anime)"

official/c43387895.lua
Fixed a false interaction when copying the name and effects of anime cards with a duplicate name but a different effect from an official card. As it was before, the official card's effects were copied, even though the anime version was targeted.
=> Small Fix for "Supreme King Dragon Starving Venom"

unofficial/c511015104.lua
Changed from 'IsExistingTarget' allow proper selection/activation
=> Fix for "Odd-Eyes Fusiongate"

unofficial/c511015106.lua
Changed from 'IsExistingTarget' allow proper selection/activation
=> Fix for "Odd-Eyes Xyzgate"

unofficial/c511015105.lua
Changed from 'IsExistingTarget' allow proper selection/activation
=> Fix for "Odd-Eyes Synchrogate"

unofficial/c511009700.lua
Card wouldn't destroy itself if the monster was Tributed or sent to the GY.
=> Fix for "Sunavalon Bloom"

unofficial/c511600207.lua
Fixed resets causing flags to disappear, as well exclude itself from the GY check to prevent incorrect handling issues (had an issue with it not destroying monsters of the right level when it was banished, as it was not in the GY upon resolution, which is in line with the text effect).
=> Fix for "Sunbloom Doom"

unofficial/c511002485.lua
Fixed monster being unable to activate Fusion Summon effect even with valid targets in Extra Deck.
=> Fix for "Soprano the Melodious Songstress (Anime)"

unofficial/c511002451.lua
Only flagged to protect controller. Fix now protects both players from damage.
=> Fix for "The World of True Darkness"

unofficial/c511002045.lua
Incorrect filter header allowed targeting of non-Level Raidraptor monsters.
=> Fix for "Raidraptor - Pain Lanius (Anime)"

proc_xyz.lua
There were some errors causing "Triangle Evolution" on a Level 10 monster unable to summon "Number XX: Utopic Dark Infinity"
=> Fix Xyz Proc for "Xyz Crown"-based effects

unofficial/c513000083.lua
Fixed issue with only allowing 1 extra attack when opponent's monster was not destroyed by battle and fixed incorrect interaction allowing battle target (monster the equipped monster was battling) to gain the multi-attack effect while still allowing the double ATK gain to occur.
=> Fix for "DZW - Chimera Clad (Anime)"

.github/CODEOWNERS
This enables automatic requests for review on PRs. The names are from observation.
Documentation: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners
=> Add CODEOWNERS [ci skip]

cards_specific_functions.lua, official/c12015000.lua, official/c12071500.lua, official/c13293158.lua, official/c21225115.lua, official/c21947653.lua, official/c22160245.lua, official/c50282757.lua, official/c58332301.lua, official/c59419719.lua, official/c59531356.lua, official/c70369116.lua, official/c85808813.lua, official/c86165817.lua, official/c86520461.lua, official/c86676862.lua, official/c94820406.lua, official/c96897184.lua
=> Update Fusion effects to match rulings for Predaplant Verte Anaconda

unofficial/c152000005.lua
Should only be able to be used when at least 2 monsters are existing in the GY or field.
=> Fix "Malevolent Malpractice"

official/c19636995.lua
Is there a reason why this card's self destruction effect can't be copied? A bug report was sent in, and I'm not sure of the answer, but being a rather common trigger effect I don't see why not, so I'm removing the UNCOPYABLE flag.
=> Fix "Red Hared Hasty Horse"

unofficial/c511001119.lua
Missing label parameter caused card to be unable to activate.
=> Fix for "Deck Destruction Virus"

official/c60018643.lua
Changed flag structure to only allow for targeting of the Summoned monsters at activation timing, not monsters summoned previously (was incorrectly targeting monsters summoned the previous turns due to incorrect group clearing)
=> Fix for "Cynet Codec"

official/c26704411.lua
Should only be able to discard "Fabled" monsters, not any "Fabled" card.
=> Fix "The Fabled Kokkator"

official/c94845226.lua
Should only be able to discard "Fabled" monsters for cost.
=> Fix for "Fabled Rudyruda"

official/c24857466.lua
It didn't check for activation legality with its trap/monster negation effect.
=> Updates/Fixes for Van'Dalgyon

unofficial/c511001792.lua
Should only inflict damage to the player(s) that do not control a face-up "Number" monster.
=> Fix for "Number Karma"

unofficial/c511002531.lua
Incorrectly allowed player to target Link Monsters in GY, and would resolve without going through effect on their side of the field.
=> Fix for "The Shallow Grave (Anime)"

official/c37129797.lua
Updated the Vampire Sucker Filter following Edo's intruction so it can trigger when Vampire sucker is summoned at the same time as another zombie monster from the gy like it should according to the following ruling: https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=21709&request_locale=ja
=> Vampire Sucker Fix

unofficial/c511009635.lua
Missing card parameter for SpElim filter caused error when attempting to activate banish from GY effect.
=> Fix for "White Aura Whale (Manga)"

unofficial/c511002746.lua
It was checking the regular location count, not the location count to summon from the extra deck.
=> Small Fix for "Advanced Heraldry Art (Anime)"

rush/c160201004.lua
fixed misplaced checks that prevented the effect from working on selected monsters other than the handler
=> Fix "Forbidding Warrior"

pre-release/c101103021.lua
Add zone checking and disallow activation if there's only 1 face-up card
=> Fix "Metalfoes Vanisher"

unofficial/c511600064.lua
Should only be able to be untargetable for attacks if another "Frightfur" monster is on the field except for "Frightfur Meister".
=> Fix for "Frightfur Meister (Manga)"

unofficial/c511600424.lua
The damop from earlier was missing. Used EFFECT_REFLECT_BATTLE_DAMAGE with the condition of it only applying when the monster is attacking, not on being attacked.
=> Fix for "Yubel - The Ultimate Nightmare (Anime)"

unofficial/c170000166.lua
Damage was only applying to Kyutora and not to other monsters controlled by the player (e4 was also contributing to the issue, and was extraneous since e2 reduced the damage to 0 anyway). Also changed it so that OCG Shunoros could not be SS'd by this effect (OCG Shunoros requires a Normal monster to be destroyed to be SS'd).
https://github.com/ProjectIgnis/CardScripts/issues/185 - In response to this issue
=> Fix for "Orichalcos Kyutora"

unofficial/c170000167.lua
ATK handling is now handled by Kyutora, and changed Summon operation to reflect needing to be Summoned by Kyutora.
=> Update "Orichalcos Shunoros (Anime)"

rush/c160003014.lua
Should set up to 1 of each "Sparks" and "Curtain of Sparks", not strictly 1 of each
=> Fix "Sparkhearts Girl"

unofficial/c511005041.lua
Removed Check/SelectRelease functions and rewrote filter to check for Tributable Continuous Trap cards
=> Fix "Traplin"

unofficial/c170000203.lua
Use of 'IsExistingTarget' was excluding valid targets in the hand.
=> Fix for "Legendary Knight Critias (Anime)"

official/c23303072.lua
Was using 'Card.IsDiscardable' in sptg, should be using s.filter to look for monsters in hand.
=> Fix for "Montage Dragon"

unofficial/c511002088.lua
Was incorrectly storing original ATK as damage value, changed to reflect any changes in ATK.
=> Fix for "Number 61: Volcasaurus (Anime)"

unofficial/c511009328.lua
Conflicting operations of skipping phase and calculating damage at end of BP made the card never enter the damage calculation operation. Added JP and corrected EN name
=> Fix for "The Phantom Knights' Round Blaze"

unofficial/c511009384.lua
Was able to attack after being Special Summoned by its own effect (should not be able to attack)
=> Update "Speedroid Rubberband Plane (Anime)"

unofficial/c511027027.lua
https://yugipedia.com/wiki/Junk_Berserker_(anime)
actually i wanted to add the anime version of "Junk Berserker" to the game to support the anime players cuz i am one of them its not fair for junk berserker in accurate character deck duel, to have an effect that destroy the defense position monsters while in the anime he hadn't , also in the anime he's attack/defense was 2500/1800 not 2700/1800 and this is was an other reason to do the anime version of him
thx
(sorry for my faults)
cdb file:
https://github.com/larry126/BabelCDB/pull/49/files
(plz dont tell me that its wrong again)
=> Add "Junk Berserker (anime)

unofficial/c511002706.lua
ATK change was resetting during EP when card proxy was not indicating such a reset existed.
=> Update "Thunder Unicorn (Anime)"

unofficial/c511600336.lua
Incorrect filter allowed selection of non-"Salamangreat" monsters
=> Fix for "Salamangreat Tail"

unofficial/c100000544.lua
Misnamed parameter was causing destroy effect to not carry through.
=> Fix for "Unsinkable Titanica"

unofficial/c511000834.lua
Should only be checking for if the opponent summons a LIGHT monster
=> Fix for "Light to the Depths"

unofficial/c511000284.lua
Should only check if there are Guardian monsters in the GY, not all Guardian cards
=> Fix for "Guardian Force"

unofficial/c100000529.lua
Incorrect card label was not allowing the position change/banish op to proceed.
=> Fix for "Valkyrie's Embrace (Anime)"

unofficial/c511000730.lua
Token procedure was not treating the tokens as Link monsters if a Link monster was SS'd
=> Fix for "Chronic Deja Vu"

unofficial/c513000014.lua
Repeated filter title was causing conflict in the Special Summon effect
=> Fix for "T.G. Halberd Cannon (Anime)"

unofficial/c511002798.lua
Should only activate if the opponent's 'Number C' monster deals damage to this card's controller, not if the controller takes damage involving a 'Number C' monster they control.
=> Fix for "Chaos Rising"

rush/c160004059.lua
Should not shuffle from GY into Deck and removed extraneous filter
=> Fix for "Jewelry Trap Hole"

unofficial/c171000111.lua
Was allowing players to draw 1 card too many from the number of materials attached to a monster.
=> Fix for "Seven Store"

unofficial/c511002509.lua
Cannot find rulings supporting sending itself to GY if it cannot be equipped to an opponent's monster by its own effect.
=> Fix for "Blast Sphere (Anime)"

unofficial/c511000086.lua
Fixed issue where an opponent's Pendulums would be deleted from the field when controller's P-Zones were full, as well as proper placement of Pendulums if they were the target.
=> Fix for "Bounce Spell"

official/c96156729.lua
Should not allow non-WIND monsters to be SS'd
=> Fix for "Windwitch Chime"

official/c50005218.lua
"tp" is needed but "p" was present.
=> Minor Fix for "Skystriker Airspace - Area Zero"

official/c42199039.lua
Changed the operation such that the script won't error anymore if you bounce the monster the card is equipped to. Although there are no official Bamboo Sword monsters, the script doesn't change a single thing when bouncing a different card. The changes are also tested thouroughly before opening this PR and I asked Hel whether this is even feasable. No objections from them, so I think I can give it a try.
Supervising staff member(s): Hel
=> Change for "Cursed Bamboo Sword"

unofficial/c511001015.lua
Should be allowed to activate even if it didn't attack an opponent's monster.
=> Update "Raidraptor Symbol"

pre-release/c101104010.lua
s.sfilter neither needs "e" nor "tp"
It's funny that I code the card correctly, somebody else makes changes and those changes aren't even needed
=> Small Fix for "Witch of the Blood Rose"

official/c51474037.lua
Changed the check in line 34 to prevent one group having all members and the other one having none.
~~Edo, check properly~~
jk friend :)
=> Small Fix for Yamoimori (again)

official/c87746184.lua
The additional confirm is only needed when sending to hand
=> Small fix for "Albion the Stigmata Dragon"

official/c19891131.lua
Unneccessary confirm slows down the game
=> Update Time Thief Regulator

unofficial/c511003047.lua
Wrong card ID caused errors on target and resolution of the negation effect.
also removed a wrong check which prevented the flag effect from being applied.
=> Fix "Crystal Wing Synchro Dragon (Anime)"

official/c35394356.lua, official/c98204536.lua, pre-release/c100278025.lua
They now take into account the Xyz Monster's current number of materials (e.g. if the Xyz Monster has no materials but needs to detach 2 for its effect, then this "instead" effect cannot be applied). The following cards were updated:
- Daruma Dropper
- Chronomaly Palace Trilithon
- ZW - Sylphid Wing
=> "Do X instead of 1 of those materials" fix

unofficial/c511003220.lua
Script for "Call of the Earthbound (Manga)"
Pedia Link: https://yugipedia.com/wiki/Ghost_Beckoning
=> Add "Call of the Earthbound (Manga)"

unofficial/c100000150.lua, unofficial/c513000004.lua
They now reset the copied effects correctly. More elaborately: The way it was before didn't reset any effects the moment a monster leaves the GY. Therefore, I adapted the procedure of the VG version and just got rid of the hardcodes since they're not needed and function properly when just copied.
The test puzzle if needed to convince yourself:
Debug.ReloadFieldBegin(DUEL_ATTACK_FIRST_TURN+DUEL_SIMPLE_AI,5)
Debug.SetPlayerInfo(0,8000,0,0)
Debug.SetPlayerInfo(1,8000,0,0)
--GY (yours)
Debug.AddCard(511000625,0,0,LOCATION_GRAVE,0,POS_FACEUP)
Debug.AddCard(13582837,0,0,LOCATION_GRAVE,0,POS_FACEUP)
Debug.AddCard(56209279,0,0,LOCATION_GRAVE,0,POS_FACEUP)
--Monster Zones (yours)
--Debug.AddCard(100000150,0,0,LOCATION_MZONE,2,POS_FACEUP_ATTACK,true) …
=> Effect Resets + Hardcode removal for "Hundred-Eyes Dragon"s

official/c72064891.lua, proc_fusion_spell.lua
Current known problems:
- Assumes that the effect with the OPT limit lets you use cards in the GY (getting the effect's `TargetRange` is impossible at the moment, but if it becomes possible in the future it could be used to determine which location you're checking).
- No way to tell (that I could find) if a Fusion Summoning effect can use the whole field or just the Monster Zones, so an effect like that of `Fullmetalfoes Alkahest` but once per turn is not currently handled (not an issue yet with the current card pool).
- Currently does not support multiple different `EFFECT_EXTRA_FUSION_MATERIAL` effects at the same time. Although this could be remedied, there is no Fusion Monster that overlaps between any 2 of them at the moment since `Cyberdark Chimera` locks you into using only Dragon …
=> Fusion procedure update to handle once per turn "EFFECT_EXTRA_FUSION_MATERIAL" effects

pre-release/c100417007.lua
The SS effect should also be usable, if the card is in the MMZ with no free zones.
=> Fix for "Ukiyoe P.U.N.K. Carp Rising"

skill/c300303009.lua
Fix effect :
During your Main Phase, you can Tribute 1 monster whose original name is "Dark Magician" to draw 2 cards.
=> Fix "Magician's Act"

unofficial/c511002813.lua
Was using ExistingTarget although the card doesn't target.
=> Small Fix for "Burial from a Different Dimension (Anime)"

unofficial/c511009136.lua, unofficial/c511009300.lua, unofficial/c700000018.lua, unofficial/c810000096.lua
"Abyss Script - Fantasy Magic (Anime)": Was using an old setcode.
"Yosen Whirlwind (Anime)": The destruction effect should be mandatory and in your turn.
"Gladiator Beast Andabata (Anime)": The atk boost should last even after battle phase.
"Neo Galaxy-Eyes Cipher Dragon (Anime)": Was not checking if there are available materials to detach.
=> Unofficial Scripts Fixes

unofficial/c511010507.lua
Shouldn't be able to put back cards if a previous zone is now occupied.
Also shouldn't set an operation info of "leave grave" if no card leaves the grave.
Supervising staff member(s): Hatter
=> Fix for "Astrograph Sorcerer (Anime)"

official/c49922726.lua
Can't use the 2nd effect if its ATK is 0.
=> Fix "Leraje the God of Archery"

unofficial/c511010507.lua
The main issue was the incorrect handling of situations where the mzone was full on resolution of the Z-ARC summon effect.
Was also missing a category and an operation info for that category.
=> Fixes for "Astrograph Sorcerer (Anime)"

goat/c504700095.lua, official/c109401.lua, official/c16719140.lua, official/c21663205.lua, official/c23912837.lua, official/c24096499.lua, official/c34124316.lua, official/c39432962.lua, official/c39581190.lua, official/c42143067.lua, official/c44311445.lua, official/c50766506.lua, official/c51205763.lua, official/c58551308.lua, official/c58911105.lua, official/c64749612.lua, official/c65046521.lua, official/c68812773.lua, official/c74762582.lua, official/c76442347.lua, official/c93775296.lua, official/c94365540.lua, pre-release/c101108021.lua
Now those cards calls will use a single call to Duel.SpecialSummon[Step] and Card.IsCanBeSpecialSummoned passing all the possible summon positions at once. This change is possible thanks to the recent change to cards like Gozen Match that will now use EFFECT_FORCE_SPSUMMON_POSITION thus allowing proper restrictions on the summoning position, no longer requiring to check both for faceup and facedown separately.
=> Update cards that can Special Summon monsters both faceup and facedown

utility.lua
Added parameter "p" for target player (needed for the "Valiant" Field Spells)
Supervising staff member(s): _fill in_
=> Update to Auxiliary.PlayFieldSpell

official/c68431965.lua
Fixes a bug where it would not be possible to activate the effects of monsters sent even if they changed their names after summoned
=> Fix "Shooting Riser Dragon"

official/c65877963.lua
Fixed a bug where it would still cause damage in the End Phase if the player summoned the Ritual monster without a Ritual Summon. This patch also fixes a bug where the damage could be prevented if the opponent performed the summon.
=> "Impcantation Chalislime" fix

official/c44335251.lua
Currently, the second effect of Souleating Oviraptor does not check whether the designated target will leave a free Main Monster Zone after being destroyed. This can lead to incorrect behaviours, as showed in the replay inside the attached .zip: if all MMZs are occupied when said effect is activated, the player can potentially target a monster in the EMZ or that is controlled by the opponent; at resolution, the target is destroyed, but the player will not be able to Special Summon a monster from the GY. In this situation, the player should be forced to only target a monster on their MMZ, in order to free up space (as also confirmed in the ruling channel of the Discord server).
This fix aims to correct this issue by calling Duel.GetMZoneCount in the s.desfilter function. …
=> Fix Souleating Oviraptor (2nd effect) - Add Duel.GetMZoneCount check for the target

official/c27918365.lua, official/c28031913.lua, official/c36492575.lua, official/c54525057.lua, official/c54658815.lua, official/c55241609.lua, official/c56003780.lua, official/c65100616.lua, official/c67127799.lua, official/c67218327.lua, official/c81524756.lua, official/c84121193.lua, official/c84899094.lua, official/c89484053.lua, official/c91557476.lua, official/c91646304.lua, official/c99674361.lua, pre-release/c101110074.lua, unofficial/c511009503.lua, unofficial/c511009617.lua, unofficial/c511018036.lua, unofficial/c511030051.lua, unofficial/c511600147.lua, unofficial/c511600262.lua, unofficial/c511600311.lua, utility.lua
Added a new auxiliary function, "Auxiliary.GetMMZonesPointedTo" (see the comments above the function for how it works).
Updated cards to use this function instead of manually having to mask a player's linked zones to only get the Main Monster Zones, while at the same time fixing some cards that need zones pointed to by a Link Monster and were also working with Link Spells up until now ("Judgment Arrows").
Some cards also received general small fixes and script polishing.
=> Update for cards that check for Main Monster Zones that Link Monsters/Cards point to

official/c68957925.lua
Link Party's script has a series of issues that this pull request aims to fix:
- The script needs to count the **original Attributes** instead of the current Attributes of Links on the field.
- The target function needs to check whether you can activate Link Party depending on the number of different original Attributes (related ruling: https://db.ygorganization.com/qa#21928)
- Ash Blossom can always respond to Link Party (even when there are not exactly 5 different original Attributes among Links), thus the effect needs to be inserted into the Ash Blossom Table.
- If Link Party is activated while there are 6 different Attributes among Links on the field, then Stardust Dragon can respond to it (according to https://db.ygorganization.com/qa#10790): the script needs to call …
=> Link Party Fix

proc_fusion_spell.lua, skill/c300302001.lua, unofficial/c511003010.lua
With the addition of https://github.com/ProjectIgnis/CardScripts/commit/1c369cb55c5ad539df704a906abb2e2060b1058f, the player can now cancel selection of the Fusion Materials and go back to selecting which Fusion Monster they want to summon with the effect.
=> Fusion Summoning procedure cancelling update 

rush/c160011033.lua, rush/c160011058.lua
- Tiger Sabre should only treat monster that are still equipped with it as Double Tribute
- Ghost Vicious cannot apply its effect to something that can already attack twice
=> fixed Tiger Sabre and Ghost Vicious

rush/c160205015.lua
- Should not be able to return the side part of a Maximum Summoned monster
- Should return all 3 cards if returning a Maximum Summoned monster
=> fixed Return of the Blaze Fiends

unofficial/c511004341.lua
This card's text is the same as the text from its 1st OCG printing, so I updated it to function the same as the OCG card.
https://yugipedia.com/wiki/Negate_Attack_(later_DM_anime)
=> Fix Negate Attack (Anime)

unofficial/c513000020.lua
Should also be usable on an opponent's DARK monster and should triple the current ATK rather than the original ATK.
https://yugipedia.com/wiki/Negative_Energy_Generator
=> Fix Negative Energy Generator

official/c14812471.lua, official/c29280589.lua, official/c31123642.lua, official/c33945211.lua, official/c33964637.lua, official/c36346532.lua, official/c44686185.lua, official/c45154513.lua, official/c46261704.lua, official/c50185950.lua, official/c54320860.lua, official/c55990317.lua, official/c5846183.lua, official/c6579928.lua, official/c66733743.lua, official/c70180284.lua, official/c70458081.lua, official/c71207871.lua, official/c7291576.lua, official/c86784733.lua, official/c91646304.lua, pre-release/c101112001.lua
Touched the monsters that, banish themselves to prevent the destruction of other cards
- Removed unnecessary HOPT flags
- Added missing REASON_REPLACE
- Use string 96 instead of card entry's own strings
- Generic formatting
=> Fix some destruction replacement effects

rush/c160205018.lua
It shouldn't be able to activate when attacking a face-down Maximum monster
=> fixed Doomblaze Despair

rush/c160012037.lua, rush/c160205061.lua
- Star Cat Destronya should not be able to Special Summon from the Deck
- Delirium Lampyris should be able to activate even if the field is full
=> fixed some rush cards

rush/c160012037.lua
Should not be able to activate with 3 or less monsters in the GY.
=> fixed Star Cat Destronya

official/c23002292.lua, official/c74577599.lua, official/c85551711.lua, unofficial/c511000427.lua
Update Red Reboot, Traptrix Holetaea, Ebon High Magician and Aid to the Doomed that require additional costs if they used such effects to be activated from the hand.
=> Update cards using EFFECT_TRAP_ACT_IN_HAND and EFFECT_QP_ACT_IN_NTPHAND

unofficial/c511027675.lua
https://yugipedia.com/wiki/D/D_Zero_Surveyor
=> Add "D/D Zero Surveyor"

pre-release/c100430002.lua
Pops the wrong group in s.spop
=> Fix for "Transcendrake Meteoros"

unofficial/c511001707.lua, unofficial/c511001765.lua
It makes more sense for it to be "Either Graveyard" instead of "Your Graveyard". Yuma only said "from the graveyard" for both.
Card database for updated "Gagaga Illusion" and "Overlay Rebirth": https://github.com/larry126/BabelCDB/pull/104
=> Fix "Gagaga Illusion" and "Overlay Rebirth"

official/c32138660.lua
Changed the way the card tracks the materials used for its summon. It now uses a flag system, so when it is flipped face-down it will properly "forget" the type of monsters used for its summon and will not retain the indestructibility effect. This should also clear up the issue with Rebirth Judgment incorrectly removing the indestructibility effect if it changes the monster type of cards in the graveyard to anything other than reptile.
The flag is using aux.Stringid(id,3), so something should be added to the cdb to give the player more info, like: "Summoned using only Reptiles."
=> Fix to Reptilianne Melusine

unofficial/c511001117.lua, unofficial/c511001123.lua, unofficial/c511001124.lua, unofficial/c511001146.lua
https://yugipedia.com/wiki/Cyberdark_Dragon_(anime)
https://yugipedia.com/wiki/Cyberdark_Keel_(anime)
https://yugipedia.com/wiki/Cyberdark_Horn_(anime)
https://yugipedia.com/wiki/Cyberdark_Edge_(anime)
1. Their equip effect should trigger on any type of summon
2. Fixed a bug where none were checking if the target to equip was not Forbidden and made accommodating changes in the Eyes Restrict equip limits
3. Made it so the target to be equipped must be a Dragon during resolution per the OCG versions since the initial OCG wording and the anime wording for this effect is quite similar
4. Removed CATEGORY_LEAVE_GRAVE Operation info per the recent Necrovalley update
5. Cyberdark Keel's burn should only trigger if it destroys specifically an opponent's monster by battle
6. Changed Cyberdark …
=> Fix Anime Cyberdarks

proc_equip.lua
Change the handling of the ruling that "Even if the effect of the activation of an Equip Spell is negated, the Spell is still equipped to the target" from the EVENT_CHAIN_SOLVING workaround to utilising the EFFECT_FLAG_CONTINUOUS_CARD.
This should resolve the bug that occurs when you target an Equip Spell with "Double Spell"
=> Update Equip Procedure

official/c24207889.lua
* Fixed an issue where the global state internal to the card would have been leaked when the card gets destroyed.
* Cleaned up the handling of the checking itself: now the card will keep track of the highest field id, and will automatically send to the GY cards with a greater id (in the case of returning to the field and changing controller, those are the only possible actions that would make a card touch the field).
* Handling of face-down monsters is "Undefined Behavior" as of now and needs to be properly investigated. At the moment if a monster is flipped by card effect it will be handled the same way as a monster that has just returned to the field or changed control.
=> Improve "There Can Be Only One" handling

rush/c160205107.lua, rush/c160207028.lua
- Doomblaze Fiend Overlord Despairacion [L]'s script should match its Over Rush counterpart
- Abysslayer Asaparas shouldn't need to Special Summon a monster to be able to destroy
=> rush card fixes

rush/c160011024.lua, rush/c160202041.lua, rush/c160207014.lua, rush/c160207017.lua
- Collapsing Chair should look at the previous attack on field to trigger
- Abyss Kraken and Abyss Poseidra need to have both their conditions fullfilled to apply their secondary effect
- Prophecy Phrase shouldn't ask about reducing ATK if it doesn't inflict damage
=> fixed some rush cards according to new rulings

rush/c160206004.lua, rush/c160206019.lua
If Tributing a monster in Maximum Mode, Maju Garzetts should use their Maximum ATK to calculate the ATK gain.
=> fix Maju Garzetts

official/c20618081.lua, official/c31313405.lua, official/c37261776.lua, official/c41463181.lua, official/c87871125.lua, official/c89662401.lua, official/c9608555.lua
Some Salamangreat cards are not listed by themselves even though they should be, so this pr is to add that to them.
Here is a list of the cards I have added `s.listed_names={id}`:
[Salamangreat Blaze Dragon](https://yugipedia.com/wiki/Salamangreat_Blaze_Dragon)
[Salamangreat Falco](https://yugipedia.com/wiki/Salamangreat_Falco)
[Salamangreat Fowl](https://yugipedia.com/wiki/Salamangreat_Fowl)
[Salamangreat Heatleo](https://yugipedia.com/wiki/Salamangreat_Heatleo)
[Salamangreat Pyro Phoenix](https://yugipedia.com/wiki/Salamangreat_Pyro_Phoenix)
[Salamangreat Sunlight Wolf](https://yugipedia.com/wiki/Salamangreat_Sunlight_Wolf)
[Salamangreat Violet Chimera](https://yugipedia.com/wiki/Salamangreat_Violet_Chimera)
=> Add `s.listed_names` to the Salamangreat cards that should have been

rush/c160012047.lua
Should not be able to activate if you control a monster in Maximum Mode
=> fixed Back to the Fusion

proc_ritual.lua
If a monster was targeted by Soul Exchange, then that monster has to be tributed as material for a Ritual Summon, handle such scenario.
~~Remaining to investigate is what to do with facedown monsters that were targeted by exchange, if to prevent the player from ritual summoning at all, or exclude those facedown cards as they can't be used as materials since they don't have their stats public.~~ ~~Make so that if one of those cards is facedown, the summon cannot be performed.~~ Facedown monsters have to be ignored.
Also some minor bugs present in the procedure have been fixed.
=> Handle EFFECT_EXTRA_RELEASE in the ritual procedure

unofficial/c511000412.lua, unofficial/c511000657.lua, unofficial/c511002520.lua, unofficial/c511002541.lua, unofficial/c511002874.lua, unofficial/c511013016.lua, unofficial/c511021000.lua, unofficial/c511600432.lua, unofficial/c513000076.lua, unofficial/c810000050.lua
1. https://yugipedia.com/wiki/Fearful_Earthbound_(manga) - Changed the condition to be at the end of the damage step to more properly respect the wording/presentation of the card in the anime/manga
2. https://yugipedia.com/wiki/Spacetime_Transcendence_(anime) - According to the dialogue (full text not visible), should only be able to summon Dinosaur monsters
3. https://yugipedia.com/wiki/Starlight_Road_(anime) - Should not be usable on your own cards
4. https://web.archive.org/web/20221025001250/https://yugipedia.com/wiki/Chthonian_Blast_(anime) - Corrected the effect based on the available text/dialogue. I also changed it to target since that seems appropriate given the nature of the effect
5. https://yugipedia.com/wiki/Jurassic_World_(anime) - Should also prevent your opponent from …
=> Unofficial Fixes

unofficial/c511027651.lua
https://yugipedia.com/wiki/Parallel_Select_(anime)
=> Add "Parallel Select (Anime)"

proc_ritual.lua, proc_workaround.lua, unofficial/c151000000.lua, utility.lua
There were many cases of the pattern `x and x or y`. Due to operator precedence this is evaluated as `(x and x) or y`. Since `x and x` is equivalent to `x` itself this can be simplified, improving clarity and sometimes removing unnecessary function calls. (don't know if Lua would optimize them anyways though)
=> Small improvement: Simplify redundant logic regarding the ternary 'or'

proc_maximum.lua, utility.lua
Moved "Card.HasDefense" to the utility file. Also added the following functions:
- Card.IsNormalSpellTrap
- Card.IsContinuousSpellTrap
- Card.IsEquipCard
- Card.IsMonsterCard
- Card.IsSpellCard
- Card.IsTrapCard
- Card.IsSpellTrapCard
- Card.IsBaseAttack
- Card.IsTextAttack
- Card.IsPreviousAttackOnField
- Card.IsBaseDefense
- Card.IsTextDefense
- Card.IsPreviousDefenseOnField
- Card.IsOriginalLevel
- Card.IsPreviousLevelOnField
- Card.IsOriginalRank
- Card.IsPreviousRankOnField
- Card.IsScale
- Card.IsPreviousAttributeOnField
- Card.IsPreviousRaceOnField
- Card.IsPreviousTypeOnField
- Card.IsPreviousCodeOnField
- Card.IsPreviousSequence
- Card.IsOwner
- Card.IsBattlePosition
- Card.HasRank
- Card.HasCounter
- Card.HasEquipCard
- Card.IsDestination
- Card.IsLeaveFieldDest
- Card.IsFieldID …
=> Added new helper functions

official/c1248895.lua
The Normal Trap "Chain Destruction", which reads...
> When a monster(s) with 2000 or less ATK is Summoned: Target 1 of them; destroy all cards with that name in its controller's hand and Main Deck.
...currently has the following issues:
- At the time of resolution, if the target left the Monster Zone between the activation and resolution of "Chain Destruction", or if it is currently in face-down Defense Position, the effect of "Chain Destruction" still destroys any available card in the hand and Main Deck of the controller, even though it shouldn't be able to. (Link to the FAQ on the Konami DB, refer to the last bulleted entry: https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=4&cid=4813)
- When a Fusion, Synchro, Xyz, or Link Monster is Summoned, "Chain Destruction" should …
=> Fix "Chain Destruction"

official/c52254878.lua
According to the Konami FAQ (https://db.ygoresources.com/card#18173), the Ignition Effect of Varis can be activated by declaring AT LEAST 1 value (among Type and Attribute) that is different from the current corresponding value of the card itself.
> At this time, either the declared Type must be different from this card's current Type, or the declared Attribute must be different from this card's current Attribute, or both.
Currently, EDOPro forces the player to declare BOTH a different Type and a different Attribute, effectively preventing them from changing only 1 property. For instance, if Varis is a Psychic/LIGHT, the current script prevents the player from declaring those two values at all: therefore, combinations like Machine/LIGHT and Psychic/DARK cannot be declared, even though …
=> Fix "Dimensional Allotrope Varis"

official/c25551951.lua
The effect of Blowback Dragon states:
> Once per turn: You can target 1 card **your opponent controls**; toss a coin 3 times and destroy **that target** if at least 2 of the results are heads.
Since it uses the wording **that target**, the effect should do nothing at resolution if the opponent is not the controller of the targeted card anymore.
The changes to the scripts are the following:
- Added a check for the target in the operation function with Card.IsControler
- Added a call to Duel.SetPossibleOperationInfo in the target function (with CATEGORY_DESTROY)
- Minor changes to modernize the scripts (replace the + operator with the | operator where applicable)
Link to the bug report Discord forum post with replay attached: https://discord.com/channels/170601678658076672/126577677578325207 …
=> Fix "Blowback Dragon"

proc_fusion.lua
https://github.com/edo9300/ygopro-core/commit/c3b5a199b42b6a8bbad9efd17b117a4647c1df02 adds an extra parameter to `EFFECT_FUSION_MATERIAL`, consisting of the effect that is performing the summon of that specific fusion monster, which is then put in the global variable Fusion.SummonEffect to be used by other scripts, needed to implement https://github.com/ProjectIgnis/CardScripts/pull/1163
=> Add Fusion.SummonEffect and handle new parameter in EFFECT_FUSION_MATERIAL

official/c81677154.lua
Add early termination condition to stop checking combinations when duplicate names are detected, reducing unnecessary computations.
Bug fixed: If you destroy a level 9 Mementotlan monster and then choose any Mementotlan monster, it will cause the game to stall for a very long time.
---
Supervising staff member(s): _fill in_
=> Fix "Mementotlan Tatsunootoshigo"

official/c23002292.lua, official/c47766694.lua, official/c57314798.lua, official/c63086455.lua, official/c64659851.lua, official/c64961254.lua, official/c67248304.lua, unofficial/c511000583.lua
The IsSSetable function now has the `target player` parameter exposed as is third parameter. Defaulting to the reason player caused problems when the player using the effect did not have a zone available, even if the player that would receive the card had one.
=> Fixed effects that set cards to the opponent's field

pre-errata/c511000228.lua
A change was made in https://github.com/ProjectIgnis/CardScripts/commit/354bf7d0dabe4833ba95838199f38772d87ec0e0 that no longer allowed this card to tribute monsters with 0 ATK for its effect, but cards of this nature were able to during that era for this type of effect.
https://ygorganization.com/ocg-011515-rulings/
https://ygorganization.com/ocg-02-08-21-rulings-update/
The 2015 article mentions a ruling for Castle Gate where you could tribute Chimeratech Fortress Dragon which has 0 original ATK, but no damage is inflicted. The 2021 article mentions the change that you can no longer tribute Chimeratech Fortress Dragon, which is in line with what's currently on the database for Castle Gate.
https://yugioh-wiki.net/index.php?%BA%DB%C4%EA%CA%D1%B9%B9#Tribute
The japanese wiki also mentions …
=> Fix Catapult Turtle (Pre-Errata)

unofficial/c511002446.lua
Fixed it so that the amount of damage in the SetOperationInfo was only being calculated based on the face-up monsters, and corrected the damage to be based on the ATK the destroyed monsters had on the field (similar card example: Time Wizard)
=> Fix Judgment of Anubis (Anime)
