ProjectIgnis/CardScripts

official/c16197610.lua
Should be able to special summon "Cloudian - Smoke Ball" from either player's GY.
=> Updated "Cloudian - Turbulence"

unofficial/c420.lua, unofficial/c511000497.lua, unofficial/c511001744.lua, unofficial/c511002013.lua, unofficial/c511002014.lua, unofficial/c511002015.lua, unofficial/c511002109.lua, unofficial/c511002487.lua, unofficial/c511002713.lua, unofficial/c511002719.lua, unofficial/c511002720.lua, unofficial/c511002822.lua, unofficial/c511009372.lua, unofficial/c511009635.lua, unofficial/c511009742.lua, unofficial/c511009743.lua, unofficial/c511009744.lua, unofficial/c511600070.lua, unofficial/c511600243.lua, unofficial/c511600249.lua, unofficial/c511600250.lua, unofficial/c700000029.lua
An overhaul to c420 (anime archetype handling) in order to utilize new functions
=> c420 (anime archetype handling) updates

unofficial/c511027010.lua
Fixed its attribute-changing effect
=> Fixed "Paradox Hydradrive Atlas".

unofficial/c511027092.lua
Fix analog to Padadox Hydradrive Atlas's.
The dice roll would'nt be able to match the attribute due to an error in the script.
=> Fixed "Judgment Roll"

unofficial/c511030008.lua, unofficial/c511030013.lua, unofficial/c511030020.lua, unofficial/c511030021.lua, unofficial/c511030023.lua, unofficial/c511030026.lua, unofficial/c511030027.lua, unofficial/c511030028.lua, unofficial/c511030035.lua, unofficial/c511030037.lua, unofficial/c511030039.lua, unofficial/c511030041.lua, unofficial/c511030044.lua, unofficial/c511030046.lua, unofficial/c511030052.lua, unofficial/c511030055.lua, unofficial/c511030056.lua, unofficial/c511030066.lua
Removed now unnecessary workarounds for HOPT handling from various unofficial cards.
=> Unofficial card updates

unofficial/c511010538.lua
https://yugipedia.com/wiki/Galactic_Charity_(anime)
=> Add "Galactic Charity (Anime)"

official/c90960358.lua
=> Fix Toon Dark Magician Girl

official/c38369349.lua
=> Fix Manga Ryu-ran

official/c53183600.lua
=> Fix Blue-Eyes Toon Dragon

unofficial/c511027108.lua
Script for the manga card "Hell Tuning"
https://yugipedia.com/wiki/Hell_Tuning
@ClementLouis 
@pyrQ 
@larry126
=> Add "Hell Tuning"

unofficial/c511027117.lua
Script for the anime version of "Gorgonic Guardian"
https://yugipedia.com/wiki/Gorgonic_Guardian_(anime)
=> Add "Gorgonic Guardian (Anime)"

unofficial/c511027102.lua
https://yugipedia.com/wiki/ZW_-_Eagle_Claw_(anime)
=> Add "ZW - Eagle Claw (anime)

unofficial/c511027118.lua
Script for "Overlay Wedge"
https://yugipedia.com/wiki/Overlay_Wedge
@ClementLouis 
@pyrQ 
@larry126
=> Add "Overlay Wedge"

unofficial/c511027107.lua
https://yugipedia.com/wiki/ZW_-_Sleipnir_Mail_(anime)
=> Add "ZW - Sleipnir Mail (anime)"

unofficial/c511027103.lua
https://yugipedia.com/wiki/ZW_-_Lightning_Blade_(anime)
Since the effect text is changed, I think that it's correct and that I can submit the card now.
=> Add "ZW - Lightning Blade (anime)"

unofficial/c511027106.lua
https://yugipedia.com/wiki/ZW_-_Tornado_Bringer_(anime)
=> Add "ZW - Tornado Bringer (anime)"

unofficial/c511027104.lua
https://yugipedia.com/wiki/ZW_-_Asura_Strike_(anime)
=> Add "ZW - Asura Strike (anime)"

unofficial/c511010039.lua
Fixed a misbehaviour when targeting Rank 0 monsters.
=> Small fix for "Utopia Roots (Anime)

unofficial/c511027110.lua
https://yugipedia.com/wiki/Acorno_(anime)
=> Add "Acorno (Anime)"

unofficial/c511027120.lua, unofficial/c511027121.lua
Scripts for the cards "Night Express Knight (Anime)" and "Rocket Express Arrow (Anime)"
Night Express - https://yugipedia.com/wiki/Night_Express_Knight_(anime)
Rocket Arrow - https://yugipedia.com/wiki/Rocket_Arrow_Express_(anime)
@larry126 
@ClementLouis 
@pyrQ
=> Add Rocket Arrow and Night Express (Anime)

c511027048.lua
Script for the anime card "Double Bind"
https://yugipedia.com/wiki/Double_Bind
@ClementLouis 
@pyrQ 
@larry126
=> Add "Double Bind"

unofficial/c511027135.lua
Script for "Poison Chain (Anime)" 
https://yugipedia.com/wiki/Poison_Chain_(anime)
@pyrQ 
@ClementLouis 
@larry126
=> Add "Poison Chain (Anime)"

unofficial/c511027111.lua
https://yugipedia.com/wiki/Dododo_Witch_(anime)
The effect is worded kinda strange.
It speaks of "activating the effect" while not having a ":" or ";".
This might need change.
=> Add "Dododo Witch (Anime)

official/c40343749.lua
Was allowing summoning 2 or more Duston monsters that you can only control 1 of. Closes #196
=> Fix "House Duston"

unofficial/c511000230.lua, unofficial/c511000231.lua, unofficial/c511000232.lua, unofficial/c511000233.lua
Update the cost function to use an auxiliary one
=> Update Number 1-4 (Anime)

unofficial/c511009080.lua
Should be able to Summon from either player's GY instead of just your own.
=> Small fix for "Ancient Gear Double Imitation"

unofficial/c511001539.lua
Fixed code to where it will allow selection of Fusion Materials and Fusion Summon of Fusion monster.
=> Fix for "Ancient Gear Hunting Hound (anime)"

official/c8148322.lua
Removed an unused cost  function to shorten the script.
=> Small "Fix" for Predaprime Fusion

unofficial/c511000467.lua
Had an incorrect code for the flag effect lines.
=> Update script for "Sand Fortress"

official/c13032689.lua, official/c13647631.lua, official/c21565445.lua, official/c28884172.lua, official/c32542011.lua, official/c32696942.lua, official/c32999573.lua, official/c35394356.lua, official/c37104630.lua, official/c45184165.lua, official/c45483489.lua, official/c55067058.lua, official/c59913418.lua, official/c62968263.lua, official/c68392533.lua, official/c706925.lua, official/c74311226.lua, official/c76722334.lua, official/c83880087.lua, official/c85668449.lua, official/c98918572.lua
Cards that trigger when detached by a cost of an Xyz monster should not trigger the effect if detached as a cost of some other card, like 'Raiders Wing"
=> Update cards that trigger when detached

unofficial/c511015106.lua
Prevented flag from resetting on Summon of Xyz monster.
=> Fixes for "Odd-Eyes Xyzgate"

unofficial/c511027002.lua
Prevented Summoning monsters from GY to EMZ
=> Fix for "Sunavalon Melias"

unofficial/c511001064.lua
=> Fix for "Ultra C"

unofficial/c511010507.lua
=> Fix for "Supreme King Z-ARC (Anime)"

pre-release/c100311003.lua
Was able to special summon itself with a full main monster zone.
=> Small Fix for "Dragunity Remus"

unofficial/c100000023.lua
Changed parameters to allow Summon with "Fossil Fusion".
=> Update "Fossil Machine Skull Convoy"

unofficial/c100000622.lua
Changed parameters to allow Summon with "Fossil Fusion".
=> Update "Fossil Machine Skull Wagon"

unofficial/c100000620.lua
Changed parameters to allow Fusion Summon with "Fossil Fusion".
=> Update "Fossil Machine Skull Buggy"

unofficial/c100000551.lua
Contact Soul doesn't target. Changed parameters to allow SS from Deck.
=> Update "Contact Soul"

unofficial/c511003202.lua, unofficial/c511003203.lua
Scripts for Heraldic Beast Basilisk and Unicorn (Anime variants)
https://yugipedia.com/wiki/Heraldic_Beast_Basilisk_(anime)
https://yugipedia.com/wiki/Heraldic_Beast_Unicorn_(anime)
@pyrQ 
@ClementLouis 
@larry126
=> Add "Heraldic Beast Basilisk/Unicorn (Anime)"

unofficial/c511027112.lua
https://yugipedia.com/wiki/Black-Winged_Dragon_(anime)
=> Add "Black-Winged Dragon (Anime)"

unofficial/c511003200.lua
Script for the Manga card "Doppler Demon Dowsing"
https://yugipedia.com/wiki/Doppler_Demon_Dowsing
@ClementLouis 
@pyrQ 
@larry126
=> Add "Doppler Demon Dowsing"

unofficial/c511003201.lua
Script for "Arcana Force EX - The Light Ruler (Anime)"
https://yugipedia.com/wiki/Arcana_Force_EX_-_The_Light_Ruler_(anime)
@ClementLouis 
@pyrQ 
@larry126
=> Add "Arcana Force EX - The Light Ruler (Anime)"

unofficial/c511001158.lua
Fixed not targeting monster in hand to Normal Summon.
=> Fix for "Necro Sacrifice"

unofficial/c511000030.lua
Removed unnecessary name checks.
=> Update "Empress's Crown (VG)"

unofficial/c511016000.lua
Changed Heads effect to reflect updated text where if an opponent's monster is destroyed by battle by any monster the controller of this card controls
=> Update "Arcana Force VII - The Chariot (Anime)"

unofficial/c511003204.lua
Script for "Empress's Crown (Anime)"
https://yugipedia.com/wiki/Empress%27s_Crown_(anime) - Pedia link
@ClementLouis 
@larry126 
@pyrQ
=> Add "Empress's Crown (Anime)"

unofficial/c513000126.lua
Updated effect to reflect changes in text.
=> Update "Arcana Force VIII - The Strength (Anime)"

unofficial/c150000000.lua
Changed scripting to better reflect update handling of forced summon positions
=> Fixes and updates for "Earthbound Tundra"

unofficial/c511002702.lua
Updated code to recognize cards in Pendulum Zones.
=> Fix for "Odd-Eyes Phantom Dragon (Manga)"

unofficial/c511003205.lua
Script for "Galaxy-Eyes Photon Dragon (Anime)"
https://yugipedia.com/wiki/Galaxy-Eyes_Photon_Dragon_(anime) - Pedia page
@larry126 
@pyrQ 
@ClementLouis
=> Add "Galaxy-Eyes Photon Dragon (Anime)"

unofficial/c511007006.lua
Updated flags to prevent script errors
=> Update "Flash Fang"

unofficial/c511001376.lua
Updated return operation to reflect new handling of pendulum zones between rule sets.
=> Fix for "D/D/D Duo-Dawn King Kali Yuga (Anime)"

unofficial/c511009403.lua
Should respond to effects from all types of cards, not just monster effects.
=> Fix for "Performapal Sky Ring"

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.md
All new pull requests will have this template text and checklist in the content box.
Also update contributing guidelines with missing BabelCDB reference and hyperlink README to said guidelines.
=> Add pull request template [ci skip]

rush/c160201016.lua
Removed line causing script errors which prevented the attack reduction from going forward.
- [ X ] I am following the [contributing guidelines](https://github.com/ProjectIgnis/CardScripts/blob/master/CONTRIBUTING.md).
=> Fix for "Royal Demon's Death Voice"

rush/c160201002.lua
https://yugipedia.com/wiki/Umekumi_of_the_Fiendish_Commander_Squad
=> Add "Umekumi of the Fiendish Commander Squad"

unofficial/c511600300.lua
Added MMZ parameter for summoning the token.
=> Fix for "The Arrival Cyberse @Ignister (Anime)"

rush/c160201038.lua
Fixed cost variable assignment and usage
=> Fix "Climax Finale"

official/c15717011.lua, official/c20951752.lua, official/c52101615.lua, official/c59160188.lua, official/c63972571.lua, official/c88696724.lua, proc_workaround.lua, unofficial/c511002661.lua, unofficial/c800000000.lua, unofficial/c95000022.lua
See details of the issue in #383
=> Fix for interaction with "Lair of Darkness"

official/c15717011.lua, official/c20951752.lua, official/c52101615.lua, official/c59160188.lua, official/c63972571.lua, official/c88696724.lua, proc_workaround.lua, unofficial/c511002661.lua, unofficial/c800000000.lua, unofficial/c95000022.lua
Reverts ProjectIgnis/CardScripts#400
=> Revert "Fix for interaction with "Lair of Darkness""

official/c15717011.lua, official/c20951752.lua, official/c52101615.lua, official/c59160188.lua, official/c63972571.lua, official/c88696724.lua, proc_workaround.lua, unofficial/c511002661.lua, unofficial/c800000000.lua, unofficial/c95000022.lua
=> Update "Lair of Darkness"

unofficial/c511000251.lua
ATK of the Tokens should be 1000, not 100
=> Fix for "Valkyrie of the Nordic Ascendant (Anime)"

unofficial/c511009935.lua
It was negating the activation of an effect not the effect itself.
=> Small fix for "Stormrider Tubieloof

pre-release/c101103021.lua
=> Fix "Metalfoes Vanisher"

rush/c160003032.lua
Enforce sending top card to GY as requirement
=> Fix "News Flash Machine Toughroid"

unofficial/c511003206.lua
Script for "Vorticular Drumgon (Anime)"
Yugipedia Link - https://yugipedia.com/wiki/Vorticular_Drumgon_(anime)
=> Add "Vorticular Drumgon (Anime)"

unofficial/c170000166.lua
Changed filter to search for Shunoros properly.
=> Fix for "Orichalcos Kyutora"

unofficial/c511003209.lua
Script for manga card "Zero Potential" 
Yugipedia Link: https://yugipedia.com/wiki/Zero_Potential
=> Add "Zero Potential"

unofficial/c511003207.lua
Script for "Hyper-Ancient Shark Megalodon (Anime)"
Yugipedia Link - https://yugipedia.com/wiki/Hyper-Ancient_Shark_Megalodon_(anime)
=> Add "Hyper-Ancient Shark Megalodon (Anime)"

unofficial/c511000885.lua
JP proxy showed general removal from field, changed condition function to reflect from only activating against banish effects.
=> Update for "Down Force"

official/c48150362.lua
Since the effect is an optional one, it needs to check whether a free monster zone is available.
=> Small fix for "Destiny Hero Drawhand"

unofficial/c511027094.lua
https://yugipedia.com/wiki/Falling_Current_(anime)
=> Add "Falling Current (Anime)"

unofficial/c511003210.lua
Script for "Toy Parade"
Pedia Link: https://yugipedia.com/wiki/Toy_Parade
=> Add "Toy Parade"

unofficial/c511003088.lua
Wasn't changing attack targets when it was attacked, this should address the issue.
=> Fix for "Battlin' Boxer Rib Gardna (Anime)"

rush/c160003058.lua
Should check if the player can draw 2.
=> Fix for "Great Turtle of Greed"

unofficial/c511027455.lua
https://yugipedia.com/wiki/Edge_Imp_Frightfuloid_(anime)
actually i have nothing to say the card is completely different so i hope you add it cuz i dont see any reason to refuse since every thing in the card is clear
thx
cdb file:
https://github.com/larry126/BabelCDB/pull/50
=> Add "Edge Imp Frightfuloid (anime)"

unofficial/c511002646.lua
Should only discard "Hell" monsters, not just "Hell" cards
=> Update "Hell Vermin Mine"

c511003211.lua
Script for "Infernity Knight (Manga)"
Pedia Link: https://yugipedia.com/wiki/Infernity_Knight_(manga)
=> Add "Infernity Knight (Manga)"

unofficial/c513000014.lua
Removed SetCountLimit and replaced with flags to deal with handling number of times effect could be used.
=> Fix for "T.G. Halberd Cannon (Anime)"

unofficial/c511009544.lua
ATK gain Pendulum effect should be OPT.
=> Fix for "Twilight Ninja Kagen (Anime)"

unofficial/c450000000.lua
Was incorrectly resetting the level.
=> Fix for "Southern Stars"

unofficial/c100000360.lua
=> Fix for "Shining Destroyer"

unofficial/c170000120.lua
Since the card ingame card text wasn't matching with the one on yugipedia, I did a complete rescript of the card.
Pedia Link: https://yugipedia.com/wiki/Fire_Recovery
=> Rescript for "Fire Recovery"

official/c63487632.lua
=> Fix for "Dragunity Arma Leyvaten"

pre-release/c101104031.lua
Now Special Summon correct Token
=> Fix Otoshidamashii

c31525442.lua, c32247099.lua, c42469671.lua, c5130393.lua, c5253985.lua, c78642798.lua, c79868386.lua
added missing scripts from [Prismatic God Box 1](https://yugipedia.com/wiki/Prismatic_God_Box)
=> added missing scripts

pre-release/c100416039.lua
Now can trigger when non-Synchro Ursartic Monster is destroyed
=> fixed "Ursarcti Quint Charge"

pre-release/c100262003.lua, pre-release/c101103000.lua, pre-release/c101103081.lua, pre-release/c101103082.lua, pre-release/c101103083.lua, pre-release/c101103084.lua, pre-release/c101103085.lua, pre-release/c101103086.lua, pre-release/c101103087.lua, pre-release/c101103088.lua, pre-release/c101103089.lua, pre-release/c101103090.lua, pre-release/c101103091.lua, pre-release/c101103092.lua, pre-release/c101103093.lua, pre-release/c101103094.lua, pre-release/c101103095.lua, pre-release/c101103096.lua, pre-release/c101103097.lua, pre-release/c101103098.lua
-War Rock Mountain
-Materiactor Gigadra
-Raging Storm Dragon - Beaufort IX
-Triphasic Dealmon Coordius
-Materiactor Gigaboros
-Steel Star Regulator
-Breath of Acclamation
-Greater Polymerization
-Reinforcement of the Army's Troops
-Psychic Eraser Laser
-Synchro Transmission
-Pendulum Encore
-Underdog
-War Rock Fortia
-War Rock Gactos
-War Rock Orpis
-War Rock Skyler
-War Rock Bashileos
-War Rock Ordeal
=> added BLOV scripts

official/c5439384.lua
=> typo Explosive Birth of the Flame Champion

unofficial/c511000131.lua
=> Small fix for "Flame Wall"

unofficial/c511000369.lua
Should have the special cost to work with Numeron Network
=> Small Fix for "Numeron Dragon (Anime)"

official/c31826057.lua, proc_workaround.lua
Only Symphonic Warrior Piaano needed the change
=> Update cards using announce race utilities

official/c23499963.lua, official/c39185163.lua, official/c46271408.lua, official/c545781.lua
=> Various fixes (mainly operation infos)

unofficial/c513000060.lua
missing operation infos, wrong card check and missing "and if you do" check
=> Fixes for "Utopia Beyond (Anime)

unofficial/c511001645.lua
Updated Fusion procedure, as currently Elemental Hero Divine Neos was unsummonable.
=> Fix "E-HERO Divine Neos (Anime)"

unofficial/c511003217.lua
Script PR for "Golden Homunculus (Anime)"
Pedia Link - https://yugipedia.com/wiki/Golden_Homunculus_(anime)
=> Add "Golden Homunculus (Anime)"

unofficial/c511003214.lua, unofficial/c511003215.lua
Script PR for "Galaxy Dragon (Manga)" and "Dragon Buster"
Galaxy Dragon Pedia Link - https://yugipedia.com/wiki/Galaxy_Dragun_(manga)
Dragon Buster Pedia Link - https://yugipedia.com/wiki/Dragon_Buster
=> Add "Galaxy Dragon (Manga)" and "Dragon Buster"

unofficial/C511003216.lua, unofficial/c511003216.lua
Script PR for "Sea Lord's Amulet (Anime)"
Pedia Link - https://yugipedia.com/wiki/Sea_Lord%27s_Amulet_(anime)
=> Add "Sea Lord's Amulet (Anime)"

unofficial/c511003213.lua
Script for Infernity Patriarch (Manga)
Pedia Link - https://yugipedia.com/wiki/Infernity_Bishop_(manga)
=> Add "Infernity Patriach (Manga)"

unofficial/c511003219.lua
Script PR for "Battlin' Boxer Cheat Commissioner (Anime)"
Pedia Link - https://yugipedia.com/wiki/Battlin%27_Boxer_Cheat_Commissioner_(anime)
=> Add "Battlin' Boxer Cheat Commissioner (Anime)"

unofficial/c500000142.lua, unofficial/c500000143.lua, unofficial/c511000148.lua, unofficial/c511000150.lua, unofficial/c511000151.lua, unofficial/c511000152.lua, unofficial/c511000153.lua
=> fix AC01 card ids for anime cards

official/c32245230.lua
=> "Contract of Destiny" fix

skill/c300303013.lua
Fixing script errors by changing some parameters and change effect to "gain LP equal to its original ATK" and not original DEF.
=>  Fix "Rise of the Fallen"

official/c9349094.lua
=> update on Sacred Tree Beast, Hyperyton

unofficial/c511003223.lua
Script for "Vow of the Sword"
Yugipedia Link: https://yugipedia.com/wiki/Vow_of_the_Sword
=> Add "Vow of the Sword"

unofficial/c511003222.lua
Script for "Meklord Emperor Granel (Anime)"
Yugipedia Link - https://yugipedia.com/wiki/Meklord_Emperor_Granel_(anime)
=> Add "Meklord Emperor Granel (Anime)"

c511003221.lua
Script for "Dark Archetype (Anime)"
Pedia Link - https://yugipedia.com/wiki/Dark_Archetype_(anime)
=> Add "Dark Archetype (Anime)"

official/c5361647.lua, unofficial/c100000601.lua
=> Small Fix for "Battlin' Boxer Glassjaw" and "Flaming Knockout"

unofficial/c511003224.lua
Script PR for "Gagaga Cowboy (Anime)"
Yugipedia Link - https://yugipedia.com/wiki/Gagaga_Cowboy_(anime)
=> Add "Gagaga Cowboy (Anime)"

unofficial/c511003226.lua
Script for "Tindangle Returner"
Yugipedia Link - https://yugipedia.com/wiki/Tindangle_Returner
=> Add "Tindangle Returner"

proc_xyz.lua
Updated the handlings of EFFECT_XYZ_MATERIAL in proc_Xyz to allow effects such as: You can use your opponent's monster for the Xyz Summon of a Utopic monster.
=> Update xyz proc to allow filter for EFFECT_XYZ_MATERIAL

official/c14799437.lua, official/c23440231.lua, official/c32617464.lua, official/c34695290.lua, official/c39468724.lua, official/c5041348.lua, official/c51849216.lua, official/c55063751.lua, official/c6182103.lua, official/c65703851.lua, official/c703897.lua, official/c72648810.lua, official/c7403341.lua, official/c75286621.lua, official/c88234821.lua, official/c99188141.lua
ydke://TdLhAGerZQF6aBECxzRIA7Q+WgKZvQoATfdwAAAoFwOrj+oDaohUBK196QU=!11ReAF3IfARFW0IF+LPxAQ==!!
=> fix cards that negate and mandatorily banish

official/c49816630.lua
The card would only trigger when the equipped monster declared an attack and it wasn't triggering when a monster attacked the equipped monster, like it should have been. This seems to have been fixed now.
=> Fix Gaiarmor Dragonshell

official/c19048328.lua
The client hint should not reset during the End Phase
=> Fix for "Chaofeng, Phantom of the Yang Zing"

official/c24487411.lua
Fixed a bug where it would only be possible to target face-up monsters with the second effect
=> Update "Detonate Deleter"

official/c28400508.lua
It was missing the location where it summons from in the OperationInfo
=> "Number 97: Draglubion"

official/c50766506.lua
Fixed a bug where it would be unable to special summon all the selected monsters
=> "Ninjutsu Art of Duplication" fix

official/c71348837.lua
removed unnecessary double confirm
=> Small change for "Madolche Salon"

rush/c160008047.lua
uses Card.IsDefensePos as the filter
=> Fix Shadow Flower Purple Smoke Spray

rush/c160007060.lua
It should work, even if a Defense Position monster is destroyed.
=> fixed Gagagaguts

rush/c160317029.lua
updated condition check so it works properly on Special Summons
=> fix Void Veil

proc_maximum.lua, rush/c160011041.lua, rush/c160011042.lua, rush/c160011043.lua, rush/c160011050.lua, rush/c160011059.lua
Also handles their interaction with Maximum monsters.
=> added Rush Equip cards

official/c73667937.lua, official/c80889750.lua
List of cards fixed:
Frightfur Sabre-Tooth\
Windwitch - Diamond Bell
=> Fix 2 cards which remembered their original materials

unofficial/c170000121.lua
https://yugipedia.com/wiki/Bonfire Updated to search Pyro monsters instead of FIRE monsters.
=> Fix Bonfire

unofficial/c511027022.lua
https://yugipedia.com/wiki/Giant%27s_Might
=> Add "Giant's Might"

unofficial/c511027030.lua
=> Add "Thunder Sea Horse (Manga)"

unofficial/c511027026.lua
https://yugipedia.com/wiki/Alchemy_Cycle_(anime)
=> Add "Alchemy Cycle (Anime)"

rush/c160011023.lua
=> added new Rush cards

unofficial/c511027011.lua
https://yugipedia.com/wiki/Release_Restraint_(anime)
=> Add Release Restraint (Anime)

unofficial/c511027028.lua, unofficial/c511027029.lua
https://yugipedia.com/wiki/The_Winged_Dragon_of_Ra_(Tag_Force_3)
https://yugipedia.com/wiki/Slifer_the_Sky_Dragon_(Tag_Force_3)
=> Add The Winged Dragon of Ra (TF3) and Slifer the Sky Dragon (TF3)

rush/c160205003.lua, rush/c160205031.lua, rush/c160205032.lua, rush/c160205033.lua, rush/c160421033.lua
Heavenly Rest now checks for original Level, according to Konami's ruling.
=> added new Rush cards + fixed Heavenly Rest

unofficial/c511003233.lua
Script for "Dragonecro Nethersoul Dragon (Manga)"
Yugipedia Link - https://yugipedia.com/wiki/Underworld_Dragon_Dragonecro_(manga)
=> Add "Dragonecro Nethersoul Dragon (Manga)"

rush/c160011041.lua, rush/c160011042.lua, rush/c160011044.lua, rush/c160205107.lua, rush/c160205108.lua, rush/c160205109.lua
- If you take control of a monster equipped with an Equip Spell that gives it piercing, attacking an opponent's monster does not deal you damage.
- Doomblaze Fiend Overlord Despairaction's alternate artwork should work properly.
=> fixed 2 issues

rush/c160011042.lua, rush/c160315011.lua
- Beta Burn Dragon should inflict 100 damage instead of 300 when a monster in Maximum Mode is on the field
- QWERTY Keyblade should apply its effect properly
=> fixed Beta Burn Dragon + QWERTY Keyblade

unofficial/c511003212.lua
Script PR for "Rousing Hydradrive Monarch"
Yugipedia Link - https://yugipedia.com/wiki/Rousing_Hydradrive_Monarch
=> Add "Rousing Hydradrive Monarch"

rush/c160011032.lua, rush/c160012026.lua
Shadow Buyer should prevent non-Fiend monsters from attacking
=> added Astrobio Dragon + fixed Shadow Buyer

rush/c160008058.lua
Should not be able to destroy a monster in Maximum Mode.
=> fixed Makiu, the Magical Mist

unofficial/c511027677.lua
https://yugipedia.com/wiki/Sharp_Pendulum_Strike
=> Add "Sharp Pendulum Strike"

unofficial/c511027673.lua
https://yugipedia.com/wiki/Exchange_of_the_Mirror_World
Supervising staff member(s): _larry126_
=> Add "Exchange of The Mirror World"

unofficial/c511027680.lua
https://yugipedia.com/wiki/Go-D/D_World
=> Add "Go-D/D World"

rush/c160005024.lua, rush/c160201015.lua, rush/c160421012.lua, rush/c160421112.lua
Cards that require being Tribute Summoned by Tributing 2 monsters should trigger if they Tribute a double-tribute monster.
=> updated some cards for new rulings

skill/c300305001.lua, skill/c300305002.lua, skill/c300305003.lua, skill/c300305004.lua, skill/c300305005.lua, skill/c300305006.lua, skill/c300305007.lua, skill/c300305008.lua, skill/c300305009.lua, skill/c300305010.lua, skill/c300305011.lua, skill/c300305012.lua
Supervising staff member(s): @pyrQ @larry126
=> Add Skills from Midterm Paradox Box

unofficial/c511027031.lua
https://yugipedia.com/wiki/All_Killing_Death_Card
=> Add Counterbalance (Manga)

unofficial/c511027692.lua
https://yugipedia.com/wiki/White_Barrier
=> Add "White Barrier"

unofficial/c511027033.lua
https://yugipedia.com/wiki/Ultimate_Ancient_Gear_Golem_(anime)
=> Add Ultimate Ancient Gear Golem (Anime)

rush/c160012050.lua, rush/c160207031.lua
Also included a small fix for Rising Luna Radiant Luster
=> added Abysslayer Vodyanoy

rush/c160013025.lua, rush/c160207015.lua, rush/c160440002.lua
- Abyss Poseidra effect that prevent Setting cards should only be applied if you have no monsters in the Graveyard. Also, cards should be able to be Set from the Graveyard regardless.
=> added new Rush cards + fixed Abyss Poseidra

proc_maximum.lua, rush/c160011056.lua
- Maximum monsters should be able to gain DEF if they are not in Maximum Mode
- The Wind Blowing Through should not draw an additionnal card if you control a monster in Maximum Mode
=> fixed interactions with Harpie Ladies

unofficial/c511003236.lua
Script for "Unformed Void (Anime)"
Yugipedia Link - https://yugipedia.com/wiki/Unformed_Void_(anime)
=> Add "Unformed Void (Anime)"

unofficial/c511003235.lua
Script for "Vehicroid Connection Zone (Anime)"
Yugipedia Link: https://yugipedia.com/wiki/Vehicroid_Connection_Zone_(anime)
=> Add "Vehicroid Connection Zone (Anime)"

unofficial/c511027541.lua
https://yugipedia.com/wiki/Speedroid_Tri-Eyed_Dice_(anime)
Supervising staff member(s): _larry126_
=> Add "Speedroid Tri-Eyed Dice (Anime)"

unofficial/c511027765.lua
https://yugipedia.com/wiki/Three_Card_Summon
Supervising staff member(s): _larry126_
=> Add "Three Card Summon"

c511027109.lua
https://yugipedia.com/wiki/Sacred_Defense_Barrier
Supervising staff member(s): larry126
=> Add "Sacred Defense Barrier (TF3)" 

unofficial/c511027654.lua
https://yugipedia.com/wiki/Superficial_Peace_(anime)
=> Add "Superficial Peace (Anime)"

unofficial/c511027782.lua
https://yugipedia.com/wiki/Natural_Disaster_(anime)
=> Add "Natural Disaster (anime)"

unofficial/c511027035.lua
https://yugipedia.com/wiki/Fortune_Lady_Earth_(anime)
=> Add Fortune Lady Earth (Anime)

unofficial/c511001423.lua
https://yugipedia.com/wiki/Glory_of_the_Seven_Emperors
The card says "Attach all banished Xyz monsters with "Number C101"....."
It doesnt say attach all your banished xyz monsters so i think it attaches from enemy banished zone as well
=> Fix "Glory of the Seven Emperors"

unofficial/c511027036.lua
https://yugipedia.com/wiki/Chain_Destruction_(manga)
=> Add Chain Destruction (Manga)

official/c10000030.lua, official/c11317977.lua, official/c21113684.lua, official/c21296502.lua, official/c22339232.lua, official/c32530043.lua, official/c34086406.lua, official/c38273745.lua, official/c40005099.lua, official/c40945356.lua, official/c581014.lua, official/c62265044.lua, official/c64245689.lua, official/c66011101.lua, official/c67616300.lua
After a recent ruling change you first pay the cost and then choose which effect to activate. If paying the cost makes an effect activatable then you can choose to activate that effect, however you still need to be able to activate at least 1 of the listed effects in order to begin the activation procedure in the first place.
Relevant rulings:
https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=11724&request_locale=ja
https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=17396&request_locale=ja
=> Updated cards with multi-choice effects that also have a cost

official/c43598843.lua, official/c48995978.lua, official/c55204071.lua, official/c79086452.lua, official/c97520532.lua
String update commit: https://github.com/ProjectIgnis/BabelCDB/commit/362c503947c73b7a2d8b43afd912ca3a51c8e946
Also includes minor bug fixes etc all around.
=> Script updates to match string updates

unofficial/c511003243.lua
Script for Damage Polarizer
Yugipedia Link: https://yugipedia.com/wiki/Damage_Polarizer_(anime)
=> Add "Damage Polarizer (Anime)"

proc_fusion_spell.lua, rush/c160020007.lua
Requires https://github.com/edo9300/ygopro-core/pull/161 to be merged.
=> added Variable Stellarizer
